// <auto-generated />
namespace zip2.DB.zip
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initialcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201508060348206_initialcreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
